site_name: Btorch
site_description: Brain-inspired torch utilities and models for neuromorphic research.
theme:
  name: readthedocs
  palette:
    - scheme: default
      primary: blue
      accent: deep orange
nav:
  - Home: index.md
docs_dir: docs
repo_url: https://github.com/Criticality-Cognitive-Computation-Lab/btorch
edit_uri: ""
